const offense = [
  {
    id: 1,
    firstName: "Tua",
    lastName: "Tagovailoa",
    src: "assets/tua_tagovailoa.png",
    position: "QB",
    depth: 1,
  },
  {
    id: 2,
    firstName: "DeVante",
    lastName: "Parker",
    src: "assets/devante_parker.png",
    position: "WR",
    depth: 1,
  },
  {
    id: 3,
    firstName: "Jaylen",
    lastName: "Waddle",
    src: "assets/jaylen_waddle.png",
    position: "WR",
    depth: 1,
  },
  {
    id: 4,
    firstName: "Jakeem",
    lastName: "Grant Sr",
    src: "assets/jakeem_grant.png",
    position: "WR",
    depth: 1,
  },
  {
    id: 5,
    firstName: "Myles",
    lastName: "Gaskin",
    src: "assets/myles_gaskin.png",
    position: "RB",
    depth: 1,
  },
  {
    id: 6,
    firstName: "Mike",
    lastName: "Gesicki",
    src: "assets/mike_gesicki.png",
    position: "TE",
    depth: 1,
  },
  {
    id: 7,
    firstName: "Austin",
    lastName: "Jackson",
    src: "assets/austin_jackson.png",
    position: "LT",
    depth: 1,
  },
  {
    id: 8,
    firstName: "Solomon",
    lastName: "Kindley",
    src: "assets/solomon_kindley.png",
    position: "LG",
    depth: 1,
  },
  {
    id: 9,
    firstName: "Michael",
    lastName: "Deiter",
    src: "assets/michael_deiter.png",
    position: "C",
    depth: 1,
  },
  {
    id: 10,
    firstName: "Robert",
    lastName: "Hunt",
    src: "assets/robert_hunt.png",
    position: "RG",
    depth: 1,
  },
  {
    id: 11,
    firstName: "Jesse",
    lastName: "Davis",
    src: "assets/jesse_davis.png",
    position: "RT",
    depth: 1,
  },
  {
    id: 12,
    firstName: "Jason",
    lastName: "Sanders",
    src: "assets/jason_sanders.png",
    position: "K",
    depth: 1,
  },
  {
    id: 13,
    firstName: "Michael",
    lastName: "Palardy",
    src: "assets/michael_palardy.png",
    position: "P",
    depth: 1,
  },
  {
    id: 14,
    firstName: "Jacoby",
    lastName: "Brissett",
    src: "assets/jacoby_brissett.png",
    position: "QB",
    depth: 2,
  },
  {
    id: 15,
    firstName: "Preston",
    lastName: "Williams",
    src: "assets/preston_williams.png",
    position: "WR",
    depth: 2,
  },
  {
    id: 16,
    firstName: "Albert",
    lastName: "Wilson",
    src: "assets/albert_wilson.png",
    position: "WR",
    depth: 2,
  },
  {
    id: 17,
    firstName: "Mack",
    lastName: "Hollins",
    src: "assets/mack_hollins.png",
    position: "WR",
    depth: 2,
  },
  {
    id: 18,
    firstName: "Malcolm",
    lastName: "Brown",
    src: "assets/malcolm_brown.png",
    position: "RB",
    depth: 2,
  },
  {
    id: 19,
    firstName: "Adam",
    lastName: "Shaheen",
    src: "assets/adam_shaheen.png",
    position: "TE",
    depth: 2,
  },
  {
    id: 20,
    firstName: "Greg",
    lastName: "Little",
    src: "assets/greg_little.png",
    position: "LT",
    depth: 2,
  },
  {
    id: 21,
    firstName: "Robert",
    lastName: "Jones",
    src: "assets/robert_jones.png",
    position: "LG",
    depth: 2,
  },
  {
    id: 22,
    firstName: "Greg",
    lastName: "Mancz",
    src: "assets/greg_mancz.png",
    position: "C",
    depth: 2,
  },
  {
    id: 23,
    firstName: "Robert",
    lastName: "Jones",
    src: "assets/robert_jones.png",
    position: "RG",
    depth: 2,
  },
  {
    id: 24,
    firstName: "Liam",
    lastName: "Eichenberg",
    src: "assets/liam_eichenberg.png",
    position: "RT",
    depth: 2,
  },
];

export default offense;
