const defense = [
  {
    id: 1,
    firstName: "Emmanuel",
    lastName: "Ogbah",
    number: 91,
    src: "assets/emmanuel_ogbah.png",
    position: "DE",
    depth: 1,
  },
  {
    id: 2,
    firstName: "Raekwon",
    lastName: "Davis",
    number: 98,
    src: "assets/raekwon_davis.png",
    position: "NT",
    depth: 1,
  },
  {
    id: 3,
    firstName: "Christian",
    lastName: "Wilkins",
    number: 94,
    src: "assets/christian_wilkins.png",
    position: "DE",
    depth: 1,
  },
  {
    id: 4,
    firstName: "Jerome",
    lastName: "Baker",
    number: 55,
    src: "assets/jerome_baker.png",
    position: "LB",
    depth: 1,
  },
  {
    id: 5,
    firstName: "Elandon",
    lastName: "Roberts",
    number: 52,
    src: "assets/elandon_roberts.png",
    position: "LB",
    depth: 1,
  },
  {
    id: 6,
    firstName: "Andrew",
    lastName: "Van Ginkel",
    number: 43,
    src: "assets/andrew_ginkel.png",
    position: "LB",
    depth: 1,
  },
  {
    id: 7,
    firstName: "Justin",
    lastName: "Coleman",
    number: 27,
    src: "assets/justin_coleman.png",
    position: "CB",
    depth: 1,
  },
  {
    id: 8,
    firstName: "Byron",
    lastName: "Jones",
    number: 24,
    src: "assets/byron_jones.png",
    position: "CB",
    depth: 1,
  },
  {
    id: 9,
    firstName: "Xavien",
    lastName: "Howard",
    number: 25,
    src: "assets/xavien_howard.png",
    position: "CB",
    depth: 1,
  },
  {
    id: 10,
    firstName: "Jason",
    lastName: "McCourty",
    number: 30,
    src: "assets/jason_mcCourty.png",
    position: "S",
    depth: 1,
  },
  {
    id: 11,
    firstName: "Eric",
    lastName: "Rowe",
    number: 21,
    src: "assets/eric_rowe.png",
    position: "S",
    depth: 1,
  },
  {
    id: 12,
    firstName: "Adam",
    lastName: "Butler",
    number: 70,
    src: "assets/adam_butler.png",
    position: "DE",
    depth: 2,
  },
  {
    id: 13,
    firstName: "John",
    lastName: "Jenkins",
    number: 90,
    src: "assets/john_jenkins.png",
    position: "NT",
    depth: 2,
  },
  {
    id: 14,
    firstName: "Zach",
    lastName: "Sieler",
    number: 92,
    src: "assets/zach_sieler.png",
    position: "DE",
    depth: 2,
  },
  {
    id: 15,
    firstName: "Duke",
    lastName: "Riley",
    number: 45,
    src: "assets/duke_riley.png",
    position: "LB",
    depth: 2,
  },
  {
    id: 16,
    firstName: "Sam",
    lastName: "Eguavoen",
    number: 49,
    src: "assets/sam_eguavoen.png",
    position: "LB",
    depth: 2,
  },
  {
    id: 17,
    firstName: "Brennan",
    lastName: "Scarlett",
    number: 57,
    src: "assets/brennan_scarlett.png",
    position: "LB",
    depth: 2,
  },
  {
    id: 18,
    firstName: "Elijah",
    lastName: "Campbell",
    number: 22,
    src: "assets/elijah_campbell.png",
    position: "CB",
    depth: 2,
  },
  {
    id: 19,
    firstName: "Noah",
    lastName: "Igbinoghene",
    number: 9,
    src: "assets/noah_igbinoghene.png",
    position: "CB",
    depth: 2,
  },
  {
    id: 20,
    firstName: "Nik",
    lastName: "Needham",
    number: 40,
    src: "assets/nik_needham.png",
    position: "CB",
    depth: 2,
  },
  {
    id: 21,
    firstName: "Jevon",
    lastName: "Holland",
    number: 8,
    src: "assets/jevon_holland.png",
    position: "S",
    depth: 2,
  },
  {
    id: 22,
    firstName: "Brandon",
    lastName: "Jones",
    number: 29,
    src: "assets/brandon_jones.png",
    position: "S",
    depth: 2,
  },
];

export default defense;
