const defense = [
  {
    id: 1,
    name: "Emmanuel Ogbah",
    src: "assets/emmanuel_ogbah.png",
    position: "DE",
    depth: 1,
  },
  {
    id: 2,
    name: "Raekwon Davis",
    src: "assets/raekwon_davis.png",
    position: "NT",
    depth: 1,
  },
  {
    id: 3,
    name: "Christian Wilkins",
    src: "assets/christian_wilkins.png",
    position: "DE",
    depth: 1,
  },
  {
    id: 4,
    name: "Jerome Baker",
    src: "assets/jerome_baker.png",
    position: "LB",
    depth: 1,
  },
  {
    id: 5,
    name: "Elandon Roberts",
    src: "assets/elandon_roberts.png",
    position: "LB",
    depth: 1,
  },
  {
    id: 6,
    name: "Andrew Van Ginkel",
    src: "assets/andrew_ginkel.png",
    position: "LB",
    depth: 1,
  },
  {
    id: 7,
    name: "Justin Coleman",
    src: "assets/justin_coleman.png",
    position: "CB",
    depth: 1,
  },
  {
    id: 8,
    name: "Byron Jones",
    src: "assets/byron_jones.png",
    position: "CB",
    depth: 1,
  },
  {
    id: 9,
    name: "Xavien Howard",
    src: "assets/xavien_howard.png",
    position: "CB",
    depth: 1,
  },
  {
    id: 10,
    name: "Jason McCourty",
    src: "assets/jason_mcCourty.png",
    position: "S",
    depth: 1,
  },
  {
    id: 11,
    name: "Eric Rowe",
    src: "assets/eric_rowe.png",
    position: "S",
    depth: 1,
  },
  {
    id: 12,
    name: "Adam Butler",
    src: "assets/adam_butler.png",
    position: "DE",
    depth: 2,
  },
  {
    id: 13,
    name: "John Jenkins",
    src: "assets/john_jenkins.png",
    position: "NT",
    depth: 2,
  },
  {
    id: 14,
    name: "Zach Sieler",
    src: "assets/zach_sieler.png",
    position: "DE",
    depth: 2,
  },
  {
    id: 15,
    name: "Duke Riley",
    src: "assets/duke_riley.png",
    position: "LB",
    depth: 2,
  },
  {
    id: 16,
    name: "Sam Eguavoen",
    src: "assets/sam_eguavoen.png",
    position: "LB",
    depth: 2,
  },
  {
    id: 17,
    name: "Brennan Scarlett",
    src: "assets/brennan_scarlett.png",
    position: "LB",
    depth: 2,
  },
  {
    id: 18,
    name: "Elijah Campbell",
    src: "assets/elijah_campbell.png",
    position: "CB",
    depth: 2,
  },
  {
    id: 19,
    name: "Noah Igbinoghene",
    src: "assets/noah_igbinoghene.png",
    position: "CB",
    depth: 2,
  },
  {
    id: 20,
    name: "Nik Needham",
    src: "assets/nik_needham.png",
    position: "CB",
    depth: 2,
  },
  {
    id: 21,
    name: "Jevon Holland",
    src: "assets/jevon_holland.png",
    position: "S",
    depth: 2,
  },
  {
    id: 22,
    name: "Brandon Jones",
    src: "assets/brandon_jones.png",
    position: "S",
    depth: 2,
  },
];

export default defense;
