const offense = [
  {
    id: 1,
    name: "Tua Tagovailoa",
    src: "assets/tua_tagovailoa.png",
    position: "QB",
    depth: 1,
  },
  {
    id: 2,
    name: "DeVante Parker",
    src: "assets/devante_parker.png",
    position: "WR",
    depth: 1,
  },
  {
    id: 3,
    name: "Jaylen Waddle",
    src: "assets/jaylen_waddle.png",
    position: "WR",
    depth: 1,
  },
  {
    id: 4,
    name: "Jakeem Grant Sr",
    src: "assets/jakeem_grant.png",
    position: "WR",
    depth: 1,
  },
  {
    id: 5,
    name: "Myles Gaskin",
    src: "assets/myles_gaskin.png",
    position: "RB",
    depth: 1,
  },
  {
    id: 6,
    name: "Mike Gesicki",
    src: "assets/mike_gesicki.png",
    position: "TE",
    depth: 1,
  },
  {
    id: 7,
    name: "Austin Jackson",
    src: "assets/austin_jackson.png",
    position: "LT",
    depth: 1,
  },
  {
    id: 8,
    name: "Solomon Kindley",
    src: "assets/solomon_kindley.png",
    position: "LG",
    depth: 1,
  },
  {
    id: 9,
    name: "Michael Deiter",
    src: "assets/michael_deiter.png",
    position: "C",
    depth: 1,
  },
  {
    id: 10,
    name: "Robert Hunt",
    src: "assets/robert_hunt.png",
    position: "RG",
    depth: 1,
  },
  {
    id: 11,
    name: "Jesse Davis",
    src: "assets/jesse_davis.png",
    position: "RT",
    depth: 1,
  },
  {
    id: 12,
    name: "Jason Sanders",
    src: "assets/jason_sanders.png",
    position: "K",
    depth: 1,
  },
  {
    id: 13,
    name: "Michael Palardy",
    src: "assets/michael_palardy.png",
    position: "P",
    depth: 1,
  },
  {
    id: 14,
    name: "Jacoby Brissett",
    src: "assets/jacoby_brissett.png",
    position: "QB",
    depth: 2,
  },
  {
    id: 15,
    name: "Preston Williams",
    src: "assets/preston_williams.png",
    position: "WR",
    depth: 2,
  },
  {
    id: 16,
    name: "Albert Wilson",
    src: "assets/albert_wilson.png",
    position: "WR",
    depth: 2,
  },
  {
    id: 17,
    name: "Mack Hollins",
    src: "assets/mack_hollins.png",
    position: "WR",
    depth: 2,
  },
  {
    id: 18,
    name: "Malcolm Brown",
    src: "assets/malcolm_brown.png",
    position: "RB",
    depth: 2,
  },
  {
    id: 19,
    name: "Adam Shaheen",
    src: "assets/adam_shaheen.png",
    position: "TE",
    depth: 2,
  },
  {
    id: 20,
    name: "Greg Little",
    src: "assets/greg_little.png",
    position: "LT",
    depth: 2,
  },
  {
    id: 21,
    name: "Robert Jones",
    src: "assets/robert_jones.png",
    position: "LG",
    depth: 2,
  },
  {
    id: 22,
    name: "Greg Mancz",
    src: "assets/greg_mancz.png",
    position: "C",
    depth: 2,
  },
  {
    id: 23,
    name: "Robert Jones",
    src: "assets/robert_jones.png",
    position: "RG",
    depth: 2,
  },
  {
    id: 24,
    name: "Liam Eichenberg",
    src: "assets/liam_eichenberg.png",
    position: "RT",
    depth: 2,
  },
];

export default offense;
